### PR TITLE
create requirements.txt and update readme.md

### PR DESCRIPTION
**Pull request by blackout314**
- create requirements.txt with missing modules
- update readme with missing cmd tool
- fix output directory problem (simplify code and test it)

### CODE REVIEW

**Review by gwen001 — COMMENTED** [review]
Added, thx

**Review by gwen001 — COMMENTED** [review]
fixed, thx

**Comment by gwen001** [comment]
I altered my own branch to fit your comments, thank you !

**Comment by blackout314** [comment]
you are welcome

**Pull request closed without merging**
